In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:/Users/USER/Desktop/URL-Phishing-Detection/datasets/clean_data_train.csv")

In [3]:
df.columns

Index(['LengthOfURL', 'DomainLengthOfURL', 'IsDomainIP', 'TLDLength',
       'URLLetterRatio', 'DigitCntInURL', 'EqualCharCntInURL',
       'QuesMarkCntInURL', 'OtherSpclCharCntInURL', 'HavingPath', 'PathLength',
       'HavingAnchor', 'HasSSL', 'IsUnreachable', 'LineOfCode', 'HasTitle',
       'HasFavicon', 'HasRobotsBlocked', 'IsResponsive', 'IsURLRedirects',
       'IsSelfRedirects', 'HasDescription', 'IsFormSubmitExternal',
       'HasSocialMediaPage', 'HasSubmitButton', 'HasHiddenFields',
       'HasPasswordFields', 'HasBankingKey', 'HasPaymentKey',
       'HasCopyrightInfoKey', 'CntImages', 'CntFilesCSS', 'CntFilesJS',
       'CntSelfHRef', 'CntEmptyRef', 'CntExternalRef', 'CntIFrame',
       'UniqueFeatureCnt', 'ShannonEntropy', 'FractalDimension',
       'KolmogorovComplexity', 'HexPatternCnt', 'Base64PatternCnt',
       'LikelinessIndex', 'Label'],
      dtype='object')

----------------URL VE SAYFA İÇERİĞİ ÖZELLİKLERİYLE -----------------------

In [4]:
df_all_feature = df

In [5]:
df_url = df

In [6]:
df_all_feature.duplicated().sum()

np.int64(29083)

In [7]:
df_all_feature = df_all_feature.drop_duplicates()

In [8]:
x = df_all_feature.drop("Label", axis=1)
y = df_all_feature["Label"].values.ravel()

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB

from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

b = BernoulliNB()
l = LogisticRegression(max_iter=1000)
d = DecisionTreeClassifier()
r = RandomForestClassifier()
gb= GradientBoostingClassifier()
kn= KNeighborsClassifier()
ab= AdaBoostClassifier()
mn= MultinomialNB()

def algo_test(x, y):
    modeller=[ b, l, d, r, gb, kn, ab, mn]
    isimler=["BernoulliNB", "LogisticRegression", "DecisionTreeClassifier", 
             "RandomForestClassifier", "GradientBoostingClassifier", "KNeighborsClassifier",
             "AdaBoostClassifier", "MultinomialNB"]

    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.3, random_state = 42)
    
    accuracy = []
    precision = []
    recall = []
    f1 = []
    mdl=[]

    print("Veriler hazır modeller deneniyor")
    for model in modeller:
        print(model, " modeli eğitiliyor!..")
        model=model.fit(x_train,y_train)
        tahmin=model.predict(x_test)
        mdl.append(model)
        accuracy.append(accuracy_score(y_test, tahmin))
        precision.append(precision_score(y_test, tahmin, average="micro"))
        recall.append(recall_score(y_test, tahmin, average="micro"))
        f1.append(f1_score(y_test, tahmin, average="micro"))
        print(confusion_matrix(y_test, tahmin))

    print("Eğitim tamamlandı.")
    
    metrics=pd.DataFrame(columns=["Accuracy", "Precision", "Recall", "F1", "Model"], index=isimler)
    metrics["Accuracy"] = accuracy
    metrics["Precision"] = precision  
    metrics["Recall"] = recall
    metrics["F1"] = f1
    metrics["Model"]=mdl

    metrics.sort_values("F1", ascending=False, inplace=True)

    print("En başarılı model: ", metrics.iloc[0].name)
    model=metrics.iloc[0,-1]
    tahmin=model.predict(np.array(x_test) if model==kn else x_test)
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, tahmin))
    print("classification Report:")
    print(classification_report(y_test, tahmin))
    print("Diğer Modeller:")
    
    return metrics.drop("Model", axis=1)

In [10]:
algo_test(x,y)

Veriler hazır modeller deneniyor
BernoulliNB()  modeli eğitiliyor!..
[[45604  2333]
 [  193 44168]]
LogisticRegression(max_iter=1000)  modeli eğitiliyor!..


C:\Users\USER\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[47591   346]
 [  367 43994]]
DecisionTreeClassifier()  modeli eğitiliyor!..
[[47878    59]
 [   76 44285]]
RandomForestClassifier()  modeli eğitiliyor!..
[[47904    33]
 [   76 44285]]
GradientBoostingClassifier()  modeli eğitiliyor!..
[[47896    41]
 [   63 44298]]
KNeighborsClassifier()  modeli eğitiliyor!..
[[47434   503]
 [  973 43388]]
AdaBoostClassifier()  modeli eğitiliyor!..
[[47757   180]
 [  185 44176]]
MultinomialNB()  modeli eğitiliyor!..
[[39235  8702]
 [  988 43373]]
Eğitim tamamlandı.
En başarılı model:  GradientBoostingClassifier
Confusion Matrix:
[[47896    41]
 [   63 44298]]
classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     47937
           1       1.00      1.00      1.00     44361

    accuracy                           1.00     92298
   macro avg       1.00      1.00      1.00     92298
weighted avg       1.00      1.00      1.00     92298

Diğer Modeller:


,Accuracy,Precision,Recall,F1
GradientBoostingClassifier,0.998873,0.998873,0.998873,0.998873
RandomForestClassifier,0.998819,0.998819,0.998819,0.998819
DecisionTreeClassifier,0.998537,0.998537,0.998537,0.998537
AdaBoostClassifier,0.996045,0.996045,0.996045,0.996045
LogisticRegression,0.992275,0.992275,0.992275,0.992275
KNeighborsClassifier,0.984008,0.984008,0.984008,0.984008
BernoulliNB,0.972632,0.972632,0.972632,0.972632
MultinomialNB,0.895014,0.895014,0.895014,0.895014


---------------- URL TABANLI ÖZELLİKLERLE EĞİTİM ALMA -----------------------

In [11]:
df_url = df_url[
    [
        # Uzunluk & Domain
        "LengthOfURL",
        "DomainLengthOfURL",
        "TLDLength",
        "IsDomainIP",

        # Karakter & Yapı
        "DigitCntInURL",
        "EqualCharCntInURL",
        "QuesMarkCntInURL",
        "OtherSpclCharCntInURL",
        "URLLetterRatio",
        "HavingPath",
        "HavingAnchor",
        "PathLength",

        # Matematiksel / Metin Karmaşıklığı
        "ShannonEntropy",
        "FractalDimension",
        "KolmogorovComplexity",
        "HexPatternCnt",
        "Base64PatternCnt",

        # Hedef
        "Label",
    ]
]

In [12]:
df_url.duplicated().sum()

np.int64(195792)

In [13]:
df_url = df_url.drop_duplicates()

In [14]:
df_url.head(10)

,LengthOfURL,DomainLengthOfURL,TLDLength,IsDomainIP,DigitCntInURL,EqualCharCntInURL,QuesMarkCntInURL,OtherSpclCharCntInURL,URLLetterRatio,HavingPath,HavingAnchor,PathLength,ShannonEntropy,FractalDimension,KolmogorovComplexity,HexPatternCnt,Base64PatternCnt,Label
0,84,76,3,0,17,0,0,4,0.655,0,0,0,4.739567,1.00,1.000000,1,3,1
1,40,20,8,1,17,0,0,6,0.250,2,0,1,3.808271,1.00,1.222222,5,3,1
2,28,19,3,0,2,0,0,3,0.536,1,0,1,4.056021,0.75,1.307692,0,2,1
3,31,23,3,0,0,0,0,3,0.677,1,0,1,3.827833,0.75,1.275862,0,2,1
4,23,15,2,0,0,0,0,2,0.391,0,0,0,3.346439,1.00,1.400000,0,2,0
5,34,25,3,0,0,0,0,4,0.647,1,0,1,3.965018,0.75,1.250000,0,3,1
6,38,30,3,0,0,0,0,4,0.579,0,0,0,3.917626,1.00,1.235294,0,3,1
7,28,20,2,0,0,0,0,1,0.536,0,0,0,3.719295,1.00,1.307692,0,2,0
8,22,7,2,0,1,0,0,2,0.500,1,0,7,4.070656,1.00,1.380952,1,2,1
9,26,18,3,0,0,0,0,1,0.500,0,0,0,3.636842,1.00,1.333333,0,2,0


In [15]:
x = df_url.drop("Label", axis=1)
y = df_url["Label"].values.ravel()

In [16]:
x.head(10)

,LengthOfURL,DomainLengthOfURL,TLDLength,IsDomainIP,DigitCntInURL,EqualCharCntInURL,QuesMarkCntInURL,OtherSpclCharCntInURL,URLLetterRatio,HavingPath,HavingAnchor,PathLength,ShannonEntropy,FractalDimension,KolmogorovComplexity,HexPatternCnt,Base64PatternCnt
0,84,76,3,0,17,0,0,4,0.655,0,0,0,4.739567,1.00,1.000000,1,3
1,40,20,8,1,17,0,0,6,0.250,2,0,1,3.808271,1.00,1.222222,5,3
2,28,19,3,0,2,0,0,3,0.536,1,0,1,4.056021,0.75,1.307692,0,2
3,31,23,3,0,0,0,0,3,0.677,1,0,1,3.827833,0.75,1.275862,0,2
4,23,15,2,0,0,0,0,2,0.391,0,0,0,3.346439,1.00,1.400000,0,2
5,34,25,3,0,0,0,0,4,0.647,1,0,1,3.965018,0.75,1.250000,0,3
6,38,30,3,0,0,0,0,4,0.579,0,0,0,3.917626,1.00,1.235294,0,3
7,28,20,2,0,0,0,0,1,0.536,0,0,0,3.719295,1.00,1.307692,0,2
8,22,7,2,0,1,0,0,2,0.500,1,0,7,4.070656,1.00,1.380952,1,2
9,26,18,3,0,0,0,0,1,0.500,0,0,0,3.636842,1.00,1.333333,0,2


In [17]:
algo_test(x,y)

Veriler hazır modeller deneniyor
BernoulliNB()  modeli eğitiliyor!..
[[ 6278   829]
 [ 4328 30850]]
LogisticRegression(max_iter=1000)  modeli eğitiliyor!..


C:\Users\USER\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[ 6671   436]
 [ 1142 34036]]
DecisionTreeClassifier()  modeli eğitiliyor!..
[[ 6826   281]
 [  255 34923]]
RandomForestClassifier()  modeli eğitiliyor!..
[[ 6932   175]
 [  206 34972]]
GradientBoostingClassifier()  modeli eğitiliyor!..
[[ 6880   227]
 [  893 34285]]
KNeighborsClassifier()  modeli eğitiliyor!..
[[ 6967   140]
 [  399 34779]]
AdaBoostClassifier()  modeli eğitiliyor!..
[[ 6657   450]
 [ 2118 33060]]
MultinomialNB()  modeli eğitiliyor!..
[[ 7097    10]
 [11511 23667]]
Eğitim tamamlandı.
En başarılı model:  RandomForestClassifier
Confusion Matrix:
[[ 6932   175]
 [  206 34972]]
classification Report:
              precision    recall  f1-score   support

           0       0.97      0.98      0.97      7107
           1       1.00      0.99      0.99     35178

    accuracy                           0.99     42285
   macro avg       0.98      0.98      0.98     42285
weighted avg       0.99      0.99      0.99     42285

Diğer Modeller:


,Accuracy,Precision,Recall,F1
RandomForestClassifier,0.990990,0.990990,0.990990,0.990990
DecisionTreeClassifier,0.987324,0.987324,0.987324,0.987324
KNeighborsClassifier,0.987253,0.987253,0.987253,0.987253
GradientBoostingClassifier,0.973513,0.973513,0.973513,0.973513
LogisticRegression,0.962682,0.962682,0.962682,0.962682
AdaBoostClassifier,0.939269,0.939269,0.939269,0.939269
BernoulliNB,0.878042,0.878042,0.878042,0.878042
MultinomialNB,0.727539,0.727539,0.727539,0.727539


In [18]:
# modelin doğruluğu hangi özelliğe daha çok bağlı olduğunu görmek için . Modele etkisini 
gb.fit(x, y)
importances = pd.Series(gb.feature_importances_, index=x.columns)
print(importances.sort_values(ascending=False).head(10))

PathLength               0.595778
DigitCntInURL            0.084813
OtherSpclCharCntInURL    0.079620
URLLetterRatio           0.064531
LengthOfURL              0.045040
TLDLength                0.032802
HavingPath               0.032376
DomainLengthOfURL        0.025536
KolmogorovComplexity     0.020070
HavingAnchor             0.013702
dtype: float64


In [19]:
# PathLength çıkarıldıktan sonra modelin doğruluk oranındaki değişiklik
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import GradientBoostingClassifier

# PathLength çıkar
x_test2 = x.drop("PathLength", axis=1)

scores = cross_val_score(
    GradientBoostingClassifier(),
    x_test2,
    y,
    cv=5,
    scoring="f1"
)

print(scores)
print("Ortalama:", scores.mean())

[0.98507334 0.982829   0.98321859 0.9829962  0.98311711]
Ortalama: 0.9834468460063615


In [20]:
# PathLength ÖNEMLİ BİR ÖZELLİK ANCAK ÇIKARILDIĞINDA MODELİN DOĞRULUĞU ÇOK DÜŞMEDİĞİ İÇİN DİĞER ÖZELLİKLERDE SONUÇTA ETKİLİ

In [21]:
df_url.duplicated().sum()

np.int64(0)